name: Build APK Docker

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build APK with official Buildozer Docker
        run: |
          docker pull ghcr.io/kivy/buildozer:latest
          docker run --rm \
            -v "$PWD":/home/user/hostcwd \
            ghcr.io/kivy/buildozer:latest \
            android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: MyApp-APK
          path: bin/*.apk
